### ISSUE TITLE
verify_pack.py: error: the following arguments are required: -d/--database

### ISSUE THREAD

**Issue by Cavia** [frederic-mahe/Hardware-Target-Game-Database#747]
Hello,

I'm getting the error `verify_pack.py: error: the following arguments are required: -d/--database` when launching verify_pack.py
The exact command issued is (following the suggested one):
`"D:\HTGDB\verify_pack.py" -f "D:\games\" -d "D:\HTGDB\SMDBs\Atari 2600 SMDB.txt" -m "D:\HTGDB\Atari2600-Mismatch.txt"`
Folders do exist and everything else.
Command is launched in cmd.exe from the following location: `D:\HTGDB>` (where the HTGDB project is installed)

It looks like the flag -d is not processed at all.
Python is Python 3.10.1 also added to PATH

Any help??

**Comment by frederic-mahe** [comment]
@Cavia sorry for taking so much time to answer. I am glad you've found a solution.

The issue you've encountered occurs only on Windows. When parsing command line arguments, if a folder name ends with a `\"`, then I think it is interpreted as an escaped `"` and not as the end of the folder name.

I don't think this is not something that can be fixed in the scripts, as the issue occurs one level above, in the shell. I can only add a warning in the documentation (commit dfb351de84d4c4afa7cbf241ed27a7c378e9f507).

I am going to close the issue. Feel free to re-open or to comment if need be.
