### ISSUE TITLE
SMS: Voyage - A Sorceress' Vacation hacks

### ISSUE THREAD

**Issue by tjanas** [frederic-mahe/Hardware-Target-Game-Database#777]
@birdybro Thank you for this large update! What is the checksum of the source rom you used for these 2 hacks?
```
Master EverDrive/4 Hacks/Voyage - A Sorceress' Vacation (Alex Kidd in Miracle World Hack) (1.05) SNAGS.sms
Master EverDrive/4 Hacks/Voyage - A Sorceress' Vacation - Catalan Version (Alex Kidd in Miracle World Hack) (1.03) SNAGS.sms
```
The reason I ask is because the old version (1.03) used `aed9aac4` (which is the one listed on [romhacking](https://www.romhacking.net/hacks/4873/)), but when I apply the 1.05 patches to that same original rom, the resulting checksum doesn't match yours.

But I'm confused because romhacking says *not* to use the Brazillian rom, and then lists the checksum of the Brazillian rom. 🙃 

Also, can we remove the old (English) 1.03 version from the SMDB now that we have 1.05?

_Originally posted by @hotelvictorcharlie in https://github.com/frederic-mahe/Hardware-Target-Game-Database/issues/775#issuecomment-1098767287_

**Comment by tjanas** [comment]
@birdybro @hotelvictorcharlie this issue has been created to handle this issue. I am also having difficulty reproducing these checksums.

**Comment by birdybro** [comment]
I used the no-intro rom for Alex Kidd in Miracle World Rev 1. That ROM isn't solely Brazilian, so I interpreted their note about not using the Brazilian one as maybe referring to some other version that wasn't listed. It's possible there is a brazilian BIOS version or a brazilian bootleg one out there somewhere, maybe a bad dump out there that they are referring to. So I used the one that romhacking.net asks for because the translation patch didn't have a separate readme or other info.

https://www.smspower.org/Hacks/AlexKiddInMiracleWorld-SMS-VoyageASorceressVacation-Mod

Also the original instructions here seem to indicate that version 1.1 (what Rev 1 roms are alternatively called) is acceptable, which is the one that No-Intro lists as being USA, Europe, Brazil. Interesting...

Here's the rom i used as a source.

![image](https://user-images.githubusercontent.com/16388068/163411247-1418ae3f-75ad-4899-beef-d466cd3fb85c.png)

And I used the online patcher on romhacking.net for both.

![image](https://user-images.githubusercontent.com/16388068/163412914-72853747-abe5-4635-8d07-e020e1548262.png)

That gave me the hashes above which match the HTGDB entry.

Also I'll remove the version 1.03, good point. Thanks!

**Comment by tjanas** [comment]
Here's the problem I'm experiencing, maybe @hotelvictorcharlie is experiencing the same: if I use the online patcher at romhacking as you described, I obtain your checksum of CABB0994. However, if I use [Lunar IPS](http://www.romhacking.net/utilities/240/) which I have always used for IPS patches, it produces a completely different file (with a different size of 524288 bytes, and checksum 76A1D277).

**Comment by hotelvictorcharlie** [comment]
Yeah I think romhacking's online patcher has a bug. It sees that the input file was 128KB, so it truncates the resulting patched rom to 128KB even though it should be 512KB. So it looks like we should go with `76a1d277`.

**Comment by hotelvictorcharlie** [comment]
```
$ crc32 patched_with_flips.sms 
76a1d277
$ dd if=patched_with_flips.sms of=truncated.sms bs=1k count=128
128+0 records in
128+0 records out
131072 bytes (131 kB, 128 KiB) copied, 0.00104748 s, 125 MB/s
$ crc32 truncated.sms 
cabb0994
```

**Comment by tjanas** [comment]
Nice catch! Where/how do we report this bug to romhacking?

**Comment by hotelvictorcharlie** [comment]
> Nice catch! Where/how do we report this bug to romhacking?

I just sent them a PR (see above), hopefully the fix will make its way to the romhacking website fairly soon (although the version there does appear to be slightly out of date vs. their GH repo).

**Comment by birdybro** [comment]
Thanks for catching this folks! I've been very busy this week and a bit drained, I'll try and catch up on anything that needs doing and fix the entry.

**Comment by davehensley** [comment]
Looks like the romhacking online patching tool has been [fixed](https://github.com/marcrobledo/RomPatcher.js/commit/af60e80985e6326efe06f5303112769c10305a3c). I just tested it with this patch and it is giving me the correct file now.

**Comment by hotelvictorcharlie** [comment]
The issue with the romhacking online patching tool has been [fixed](https://github.com/marcrobledo/RomPatcher.js/commit/af60e80985e6326efe06f5303112769c10305a3c) now. I just tested it with this patch and it gave me the correct file.
